### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by X-dark** [Vitozz/cppAlsaVolume#1]
After some time, alsavolume segfaults with a `Too many open files` error.
I use the latest version on ArchLinux.

**Comment by X-dark** [comment]
lsof gives me a constantly increasing number of handle for `/dev/snd/controlC0`

**Comment by Vitozz** [comment]
I'm working on this problem. The simple solution is to disable "sound monitoring" in options

**Comment by X-dark** [comment]
Yes, but it kind of defeat the purpose I am using AlsaVolume for: being able to know quickly if my speakers are muted or not.

**Comment by Vitozz** [comment]
I've made some fixes ( there were memory leaks ) this should fix segmentation faults.

**Comment by X-dark** [comment]
Yes it seems to be better. Thanks.
